# Generated by Django 3.1.4 on 2020-12-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.CharField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('abstract', models.CharField(max_length=1000, null=True)),
                ('journal', models.CharField(max_length=1000, null=True)),

                ('conclusions', models.CharField(max_length=1000, null=True)),
                ('results', models.CharField(max_length=1000, null=True)),
                ('copyrights', models.CharField(max_length=1000, null=True)),
                ('doi', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
