# Generated by Django 3.1.4 on 2020-12-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='conclusions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='copyrights',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='results',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
