# Generated by Django 3.1.4 on 2020-12-10 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.JSONField(default=list, null=True),
        ),

        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='conclusions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='copyrights',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pubmed_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='results',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
