# Generated by Django 3.1.4 on 2020-12-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201208_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='pubmed_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
