# Generated by Django 3.1.4 on 2020-12-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201210_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(default=150000, primary_key=True, serialize=False),
        ),
    ]
