# Generated by Django 3.1.4 on 2020-12-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('definition', models.CharField(max_length=5000, verbose_name='Definition')),
            ],
        ),
    ]
