# Generated by Django 3.1.4 on 2020-12-19 07:20

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=500, null=True, verbose_name='Class')),
                ('parent_id', djongo.models.fields.JSONField(default=list, null=True, verbose_name='Subclass of')),
                ('label', models.CharField(max_length=500, verbose_name='Label')),
                ('definition', models.CharField(max_length=5000, null=True, verbose_name='Definition')),
                ('synonymous', djongo.models.fields.JSONField(default=list, null=True)),
            ],
        ),
    ]
